spring:
  profiles:
    active: prod #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ddzbSecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
http:
  port: 8085 # http服务端口

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "ddzb:"
    expire:
      authCode: 60 # 验证码超期时间 60秒  未使用

logging:
  config:
    - classpath:logback-spring.xml
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.ddzb.coppermall: debug

